/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformAssetContentToJSON = function (value: AssetContent): any {
    return {
        url: value.url,
        format: value.format,
        density: value.density
    }
}

export const transformJSONToAssetContent = function (value: any): AssetContent {
    return {
        url: value.url,
        format: value.format,
        density: value.density
    }
}

/**
 * 
 * @export
 * @interface AssetContent
 */
export interface AssetContent {
    /**
     * URL of the asset content
     * @type {string}
     * @memberof AssetContent
     */
    url: string;
    /**
     * Format of the asset content
     * @type {string}
     * @memberof AssetContent
     */
    format: 'png' | 'jpg' | 'svg' | 'pdf';
    /**
     * Density of the asset content
     * @type {number}
     * @memberof AssetContent
     */
    density?: 1 | 1.5 | 2 | 3 | 4;
}


