/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformBlendModeEnumToJSON = function (value: BlendModeEnum): any {
    return value;
}

export const transformJSONToBlendModeEnum = function (value: any): BlendModeEnum {
    return value;
}

/**
 * 
 * @export
 * @enum {string}
 */
export enum BlendModeEnum {
    NORMAL = 'normal',
    DARKEN = 'darken',
    MULTIPLY = 'multiply',
    COLOR_BURN = 'color-burn',
    LIGHTEN = 'lighten',
    SCREEN = 'screen',
    COLOR_DODGE = 'color-dodge',
    OVERLAY = 'overlay',
    SOFT_LIGHT = 'soft-light',
    HARD_LIGHT = 'hard-light',
    DIFFERENCE = 'difference',
    EXCLUSION = 'exclusion',
    HUE = 'hue',
    SATURATION = 'saturation',
    COLOR = 'color',
    LUMINOSITY = 'luminosity',
    SOURCE_IN = 'source-in',
    SOURCE_OUT = 'source-out',
    SOURCE_ATOP = 'source-atop',
    DESTINATION_OVER = 'destination-over',
    DESTINATION_IN = 'destination-in',
    DESTINATION_OUT = 'destination-out',
    DESTINATION_ATOP = 'destination-atop',
    DISSOLVE = 'dissolve',
    LINEAR_BURN = 'linear-burn',
    LINEAR_DODGE = 'linear-dodge',
    DARKER_COLOR = 'darker-color',
    LIGHTER_COLOR = 'lighter-color',
    VIVID_LIGHT = 'vivid-light',
    LINEAR_LIGHT = 'linear-light',
    PIN_LIGHT = 'pin-light',
    HARD_MIX = 'hard-mix',
    SUBTRACT = 'subtract',
    DIVIDE = 'divide'
}


