/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformComponentSectionVariantPropertyToJSON = function (value: ComponentSectionVariantProperty): any {
    return {
        id: value.id,
        name: value.name,
        values: value.values
    }
}

export const transformJSONToComponentSectionVariantProperty = function (value: any): ComponentSectionVariantProperty {
    return {
        id: value.id,
        name: value.name,
        values: value.values
    }
}

/**
 * 
 * @export
 * @interface ComponentSectionVariantProperty
 */
export interface ComponentSectionVariantProperty {
    /**
     * Unique id of the variant property
     * @type {string}
     * @memberof ComponentSectionVariantProperty
     */
    id: string;
    /**
     * Name of the variant property (e.g. `“type”`, `“state”`, etc.)
     * @type {string}
     * @memberof ComponentSectionVariantProperty
     */
    name: string;
    /**
     * Possible values that the property can take (e.g. `[\"default\", \"hover\", \"pressed\"]`)
     * @type {Array<string>}
     * @memberof ComponentSectionVariantProperty
     */
    values: Array<string>;
}


