/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ColorData,
    transformColorDataToJSON,
    transformJSONToColorData
} from './color-data';
import {
    Link,
    transformLinkToJSON,
    transformJSONToLink
} from './link';
import {
    SourceEnum,
    transformSourceEnumToJSON,
    transformJSONToSourceEnum
} from './source-enum';
import {
    Thumbnails,
    transformThumbnailsToJSON,
    transformJSONToThumbnails
} from './thumbnails';
import {
    User,
    transformUserToJSON,
    transformJSONToUser
} from './user';
import {
    VersionCommit,
    transformVersionCommitToJSON,
    transformJSONToVersionCommit
} from './version-commit';


export const transformComponentVersionSummaryToJSON = function (value: ComponentVersionSummary): any {
    return {
        id: value.id,
        creator: value.creator && transformUserToJSON(value.creator),
        commit: value.commit && transformVersionCommitToJSON(value.commit),
        image_url: value.imageUrl,
        thumbnails: value.thumbnails && transformThumbnailsToJSON(value.thumbnails),
        source: transformSourceEnumToJSON(value.source),
        width: value.width,
        height: value.height,
        background_color: value.backgroundColor && transformColorDataToJSON(value.backgroundColor),
        density_scale: value.densityScale,
        links: value.links.map(transformLinkToJSON),
        created: value.created
    }
}

export const transformJSONToComponentVersionSummary = function (value: any): ComponentVersionSummary {
    return {
        id: value.id,
        creator: value.creator && transformJSONToUser(value.creator),
        commit: value.commit && transformJSONToVersionCommit(value.commit),
        imageUrl: value.image_url,
        thumbnails: value.thumbnails && transformJSONToThumbnails(value.thumbnails),
        source: transformJSONToSourceEnum(value.source),
        width: value.width,
        height: value.height,
        backgroundColor: value.background_color && transformJSONToColorData(value.background_color),
        densityScale: value.density_scale,
        links: value.links.map(transformJSONToLink),
        created: value.created
    }
}

/**
 * 
 * @export
 * @interface ComponentVersionSummary
 */
export interface ComponentVersionSummary {
    /**
     * The unique id of the version
     * @type {string}
     * @memberof ComponentVersionSummary
     */
    id: string;
    /**
     * 
     * @type {User}
     * @memberof ComponentVersionSummary
     */
    creator?: User;
    /**
     * 
     * @type {VersionCommit}
     * @memberof ComponentVersionSummary
     */
    commit?: VersionCommit;
    /**
     * URL of the image for the version
     * @type {string}
     * @memberof ComponentVersionSummary
     */
    imageUrl: string;
    /**
     * 
     * @type {Thumbnails}
     * @memberof ComponentVersionSummary
     */
    thumbnails?: Thumbnails;
    /**
     * 
     * @type {SourceEnum}
     * @memberof ComponentVersionSummary
     */
    source: SourceEnum;
    /**
     * Width of the version
     * @type {number}
     * @memberof ComponentVersionSummary
     */
    width: number;
    /**
     * Height of the version
     * @type {number}
     * @memberof ComponentVersionSummary
     */
    height: number;
    /**
     * 
     * @type {ColorData}
     * @memberof ComponentVersionSummary
     */
    backgroundColor?: ColorData;
    /**
     * Pixel density
     * @type {number}
     * @memberof ComponentVersionSummary
     */
    densityScale: number;
    /**
     * 
     * @type {Array<Link>}
     * @memberof ComponentVersionSummary
     */
    links: Array<Link>;
    /**
     * The unix timestamp when the component version was created
     * @type {number}
     * @memberof ComponentVersionSummary
     */
    created: number;
}


