/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformConnectedComponentLinkToJSON = function (value: ConnectedComponentLink): any {
    return {
        type: value.type,
        url: value.url,
        name: value.name
    }
}

export const transformJSONToConnectedComponentLink = function (value: any): ConnectedComponentLink {
    return {
        type: value.type,
        url: value.url,
        name: value.name
    }
}

/**
 * 
 * @export
 * @interface ConnectedComponentLink
 */
export interface ConnectedComponentLink {
    /**
     * Type of the link
     * @type {string}
     * @memberof ConnectedComponentLink
     */
    type: 'custom' | 'github' | 'gitlab' | 'bitbucket' | 'storybook' | 'styleguidist';
    /**
     * Url of the link
     * @type {string}
     * @memberof ConnectedComponentLink
     */
    url: string;
    /**
     * Name for custom links
     * @type {string}
     * @memberof ConnectedComponentLink
     */
    name?: string;
}


