/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformDesignTokenResourceToJSON = function (value: DesignTokenResource): any {
    return {
        id: value.id,
        type: value.type
    }
}

export const transformJSONToDesignTokenResource = function (value: any): DesignTokenResource {
    return {
        id: value.id,
        type: value.type
    }
}

/**
 * Details of the resource that the design token is generated from.
 * @export
 * @interface DesignTokenResource
 */
export interface DesignTokenResource {
    /**
     * The unique id of the resource
     * @type {string}
     * @memberof DesignTokenResource
     */
    id: string;
    /**
     * The type of the resource
     * @type {string}
     * @memberof DesignTokenResource
     */
    type: 'Color' | 'TextStyle' | 'SpacingToken';
}


