/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformEnabledRemPreferencesToJSON = function (value: EnabledRemPreferences): any {
    return {
        status: value.status,
        root_font_size: value.rootFontSize,
        use_for_font_sizes: value.useForFontSizes,
        use_for_measurements: value.useForMeasurements
    }
}

export const transformJSONToEnabledRemPreferences = function (value: any): EnabledRemPreferences {
    return {
        status: value.status,
        rootFontSize: value.root_font_size,
        useForFontSizes: value.use_for_font_sizes,
        useForMeasurements: value.use_for_measurements
    }
}

/**
 * 
 * @export
 * @interface EnabledRemPreferences
 */
export interface EnabledRemPreferences {
    /**
     * The status of the preferences
     * @type {string}
     * @memberof EnabledRemPreferences
     */
    status: 'enabled';
    /**
     * Font size of the root element
     * @type {number}
     * @memberof EnabledRemPreferences
     */
    rootFontSize: number;
    /**
     * Whether rem unit is used for font sizes
     * @type {boolean}
     * @memberof EnabledRemPreferences
     */
    useForFontSizes: boolean;
    /**
     * Whether rem unit is used for measurements
     * @type {boolean}
     * @memberof EnabledRemPreferences
     */
    useForMeasurements: boolean;
}


