/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    EntityReference,
    transformEntityReferenceToJSON,
    transformJSONToEntityReference
} from './entity-reference';
import {
    FlowBoardPosition,
    transformFlowBoardPositionToJSON,
    transformJSONToFlowBoardPosition
} from './flow-board-position';


export const transformFlowBoardVariantGroupNodeToJSON = function (value: FlowBoardVariantGroupNode): any {
    return {
        id: value.id,
        type: value.type,
        position: transformFlowBoardPositionToJSON(value.position),
        variant_group: transformEntityReferenceToJSON(value.variantGroup),
        default_variant: transformEntityReferenceToJSON(value.defaultVariant)
    }
}

export const transformJSONToFlowBoardVariantGroupNode = function (value: any): FlowBoardVariantGroupNode {
    return {
        id: value.id,
        type: value.type,
        position: transformJSONToFlowBoardPosition(value.position),
        variantGroup: transformJSONToEntityReference(value.variant_group),
        defaultVariant: transformJSONToEntityReference(value.default_variant)
    }
}

/**
 * 
 * @export
 * @interface FlowBoardVariantGroupNode
 */
export interface FlowBoardVariantGroupNode {
    /**
     * The unique id of the variant group node
     * @type {string}
     * @memberof FlowBoardVariantGroupNode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FlowBoardVariantGroupNode
     */
    type: 'VariantGroup';
    /**
     * 
     * @type {FlowBoardPosition}
     * @memberof FlowBoardVariantGroupNode
     */
    position: FlowBoardPosition;
    /**
     * 
     * @type {EntityReference}
     * @memberof FlowBoardVariantGroupNode
     */
    variantGroup: EntityReference;
    /**
     * 
     * @type {EntityReference}
     * @memberof FlowBoardVariantGroupNode
     */
    defaultVariant: EntityReference;
}


