/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    FlowBoardNodeColor,
    transformFlowBoardNodeColorToJSON,
    transformJSONToFlowBoardNodeColor
} from './flow-board-node-color';
import {
    FlowBoardPosition,
    transformFlowBoardPositionToJSON,
    transformJSONToFlowBoardPosition
} from './flow-board-position';
import {
    ScreenAnnotationNoteType,
    transformScreenAnnotationNoteTypeToJSON,
    transformJSONToScreenAnnotationNoteType
} from './screen-annotation-note-type';


export const transformFlowBoardAnnotationNodeToJSON = function (value: FlowBoardAnnotationNode): any {
    return {
        id: value.id,
        type: value.type,
        position: transformFlowBoardPositionToJSON(value.position),
        width: value.width,
        height: value.height,
        color: transformFlowBoardNodeColorToJSON(value.color),
        font_size: value.fontSize,
        font_type: value.fontType,
        text: value.text,
        note_type: value.noteType && transformScreenAnnotationNoteTypeToJSON(value.noteType)
    }
}

export const transformJSONToFlowBoardAnnotationNode = function (value: any): FlowBoardAnnotationNode {
    return {
        id: value.id,
        type: value.type,
        position: transformJSONToFlowBoardPosition(value.position),
        width: value.width,
        height: value.height,
        color: transformJSONToFlowBoardNodeColor(value.color),
        fontSize: value.font_size,
        fontType: value.font_type,
        text: value.text,
        noteType: value.note_type && transformJSONToScreenAnnotationNoteType(value.note_type)
    }
}

/**
 * 
 * @export
 * @interface FlowBoardAnnotationNode
 */
export interface FlowBoardAnnotationNode {
    /**
     * The unique id of the screen node
     * @type {string}
     * @memberof FlowBoardAnnotationNode
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FlowBoardAnnotationNode
     */
    type: 'AnnotationNode';
    /**
     * 
     * @type {FlowBoardPosition}
     * @memberof FlowBoardAnnotationNode
     */
    position: FlowBoardPosition;
    /**
     * 
     * @type {number}
     * @memberof FlowBoardAnnotationNode
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof FlowBoardAnnotationNode
     */
    height: number;
    /**
     * 
     * @type {FlowBoardNodeColor}
     * @memberof FlowBoardAnnotationNode
     */
    color: FlowBoardNodeColor;
    /**
     * 
     * @type {string}
     * @memberof FlowBoardAnnotationNode
     */
    fontSize: 'small' | 'medium' | 'large' | 'xlarge';
    /**
     * 
     * @type {string}
     * @memberof FlowBoardAnnotationNode
     */
    fontType: 'simple' | 'book-style' | 'technical' | 'handwritten';
    /**
     * The text content of the annotation
     * @type {string}
     * @memberof FlowBoardAnnotationNode
     */
    text: string;
    /**
     * 
     * @type {ScreenAnnotationNoteType}
     * @memberof FlowBoardAnnotationNode
     */
    noteType?: ScreenAnnotationNoteType;
}


