/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    EntityReference,
    transformEntityReferenceToJSON,
    transformJSONToEntityReference
} from './entity-reference';
import {
    FlowBoardNodeColor,
    transformFlowBoardNodeColorToJSON,
    transformJSONToFlowBoardNodeColor
} from './flow-board-node-color';
import {
    FlowBoardPosition,
    transformFlowBoardPositionToJSON,
    transformJSONToFlowBoardPosition
} from './flow-board-position';
import {
    FlowBoardScreenNode,
    transformFlowBoardScreenNodeToJSON,
    transformJSONToFlowBoardScreenNode
} from './flow-board-screen-node';
import {
    FlowBoardShapeNode,
    transformFlowBoardShapeNodeToJSON,
    transformJSONToFlowBoardShapeNode
} from './flow-board-shape-node';
import {
    FlowBoardTextNode,
    transformFlowBoardTextNodeToJSON,
    transformJSONToFlowBoardTextNode
} from './flow-board-text-node';
import {
    FlowBoardVariantGroupNode,
    transformFlowBoardVariantGroupNodeToJSON,
    transformJSONToFlowBoardVariantGroupNode
} from './flow-board-variant-group-node';


export const transformJSONToFlowBoardNode = function (value: any): FlowBoardNode {
    switch (value.type) {
        case 'ScreenNode':
            return transformJSONToFlowBoardScreenNode(value);
        case 'ShapeNode':
            return transformJSONToFlowBoardShapeNode(value);
        case 'TextLabelNode':
            return transformJSONToFlowBoardTextNode(value);
        case 'VariantGroupNode':
            return transformJSONToFlowBoardVariantGroupNode(value);
        default:
            throw new Error(`No variant of FlowBoardNode exists with 'type=${ value.type }'`);
    }
}

export const transformFlowBoardNodeToJSON = function (value: FlowBoardNode): any {
    switch (value.type) {
        case 'ScreenNode':
            return transformFlowBoardScreenNodeToJSON(value);
        case 'ShapeNode':
            return transformFlowBoardShapeNodeToJSON(value);
        case 'TextLabelNode':
            return transformFlowBoardTextNodeToJSON(value);
        case 'VariantGroupNode':
            return transformFlowBoardVariantGroupNodeToJSON(value);
    }
}

/**
 * @type FlowBoardNode
 * @export
 */
export type FlowBoardNode = FlowBoardScreenNode | FlowBoardShapeNode | FlowBoardTextNode | FlowBoardVariantGroupNode;


