/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformFlowBoardToJSON = function (value: FlowBoard): any {
    return {
        id: value.id,
        name: value.name,
        number_of_connectors: value.numberOfConnectors,
        number_of_nodes: value.numberOfNodes,
        number_of_groups: value.numberOfGroups
    }
}

export const transformJSONToFlowBoard = function (value: any): FlowBoard {
    return {
        id: value.id,
        name: value.name,
        numberOfConnectors: value.number_of_connectors,
        numberOfNodes: value.number_of_nodes,
        numberOfGroups: value.number_of_groups
    }
}

/**
 * 
 * @export
 * @interface FlowBoard
 */
export interface FlowBoard {
    /**
     * Identifier of the board
     * @type {string}
     * @memberof FlowBoard
     */
    id: string;
    /**
     * Name of the board
     * @type {string}
     * @memberof FlowBoard
     */
    name: string;
    /**
     * Number of connectors in the board
     * @type {number}
     * @memberof FlowBoard
     */
    numberOfConnectors: number;
    /**
     * Number of nodes in the board
     * @type {number}
     * @memberof FlowBoard
     */
    numberOfNodes: number;
    /**
     * Number of groups in the board
     * @type {number}
     * @memberof FlowBoard
     */
    numberOfGroups: number;
}


