/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ColorData,
    transformColorDataToJSON,
    transformJSONToColorData
} from './color-data';


export const transformFlowBoardGroupToJSON = function (value: FlowBoardGroup): any {
    return {
        id: value.id,
        created: value.created,
        name: value.name,
        color: transformColorDataToJSON(value.color)
    }
}

export const transformJSONToFlowBoardGroup = function (value: any): FlowBoardGroup {
    return {
        id: value.id,
        created: value.created,
        name: value.name,
        color: transformJSONToColorData(value.color)
    }
}

/**
 * 
 * @export
 * @interface FlowBoardGroup
 */
export interface FlowBoardGroup {
    /**
     * Identifier of the flow board group
     * @type {string}
     * @memberof FlowBoardGroup
     */
    id: string;
    /**
     * The unix timestamp when the color was created
     * @type {number}
     * @memberof FlowBoardGroup
     */
    created: number;
    /**
     * Name of the flow board
     * @type {string}
     * @memberof FlowBoardGroup
     */
    name: string;
    /**
     * 
     * @type {ColorData}
     * @memberof FlowBoardGroup
     */
    color: ColorData;
}


