/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ColorStop,
    transformColorStopToJSON,
    transformJSONToColorStop
} from './color-stop';


export const transformGradientToJSON = function (value: Gradient): any {
    return {
        type: value.type,
        angle: value.angle,
        scale: value.scale,
        color_stops: value.colorStops && value.colorStops.map(transformColorStopToJSON),
        opacity: value.opacity
    }
}

export const transformJSONToGradient = function (value: any): Gradient {
    return {
        type: value.type,
        angle: value.angle,
        scale: value.scale,
        colorStops: value.color_stops && value.color_stops.map(transformJSONToColorStop),
        opacity: value.opacity
    }
}

/**
 * 
 * @export
 * @interface Gradient
 */
export interface Gradient {
    /**
     * Type of the gradient
     * @type {string}
     * @memberof Gradient
     */
    type?: 'linear' | 'radial' | 'angular';
    /**
     * Angle of the gradient
     * @type {number}
     * @memberof Gradient
     */
    angle?: number;
    /**
     * Scale of the gradient
     * @type {number}
     * @memberof Gradient
     */
    scale?: number;
    /**
     * 
     * @type {Array<ColorStop>}
     * @memberof Gradient
     */
    colorStops?: Array<ColorStop>;
    /**
     * Opacity of the gradient
     * @type {number}
     * @memberof Gradient
     */
    opacity?: number;
}


