/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformLanguageEnumToJSON = function (value: LanguageEnum): any {
    return value;
}

export const transformJSONToLanguageEnum = function (value: any): LanguageEnum {
    return value;
}

/**
 * Programming language
 * @export
 * @enum {string}
 */
export enum LanguageEnum {
    MARKUP = 'markup',
    HTML = 'html',
    XML = 'xml',
    SVG = 'svg',
    CSS = 'css',
    CLIKE = 'clike',
    JAVASCRIPT = 'javascript',
    ACTIONSCRIPT = 'actionscript',
    C = 'c',
    CS = 'cs',
    CPP = 'cpp',
    COFFEESCRIPT = 'coffeescript',
    DART = 'dart',
    EJS = 'ejs',
    ELM = 'elm',
    ERB = 'erb',
    FLOW = 'flow',
    FTL = 'ftl',
    HANDLEBARS = 'handlebars',
    JAVA = 'java',
    KOTLIN = 'kotlin',
    LESS = 'less',
    LIVESCRIPT = 'livescript',
    MARKDOWN = 'markdown',
    OBJECTIVEC = 'objectivec',
    PHP = 'php',
    PUG = 'pug',
    PYTHON = 'python',
    R = 'r',
    JSX = 'jsx',
    TSX = 'tsx',
    SASS = 'sass',
    SCSS = 'scss',
    SCALA = 'scala',
    SWIFT = 'swift',
    TS = 'ts',
    VELOCITY = 'velocity',
    YAML = 'yaml'
}


