/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformLayerConstraintsHorizontalToJSON = function (value: LayerConstraintsHorizontal): any {
    return {
        sizing_mode: value.sizingMode,
        min: value.min,
        max: value.max
    }
}

export const transformJSONToLayerConstraintsHorizontal = function (value: any): LayerConstraintsHorizontal {
    return {
        sizingMode: value.sizing_mode,
        min: value.min,
        max: value.max
    }
}

/**
 * Horizontal resizing constraint
 * @export
 * @interface LayerConstraintsHorizontal
 */
export interface LayerConstraintsHorizontal {
    /**
     * Sizing mode of the layer along the axis
     * @type {string}
     * @memberof LayerConstraintsHorizontal
     */
    sizingMode?: 'fixed' | 'stretch' | 'hug-contents';
    /**
     * Indicates whether the layer is pinned to the minimum edge of the axis
     * @type {boolean}
     * @memberof LayerConstraintsHorizontal
     */
    min?: boolean;
    /**
     * Indicates whether the layer is pinned to the maximum edge of the axis
     * @type {boolean}
     * @memberof LayerConstraintsHorizontal
     */
    max?: boolean;
}


