/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformLayerGridSizeToJSON = function (value: LayerGridSize): any {
    return {
        type: value.type,
        value: value.value
    }
}

export const transformJSONToLayerGridSize = function (value: any): LayerGridSize {
    return {
        type: value.type,
        value: value.value
    }
}

/**
 * Size of a column or row in a grid layout
 * @export
 * @interface LayerGridSize
 */
export interface LayerGridSize {
    /**
     * Type of the grid track size
     * @type {string}
     * @memberof LayerGridSize
     */
    type?: 'fixed' | 'flex';
    /**
     * Size value of the grid track
     * @type {number}
     * @memberof LayerGridSize
     */
    value?: number;
}


