/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    BlendModeEnum,
    transformBlendModeEnumToJSON,
    transformJSONToBlendModeEnum
} from './blend-mode-enum';
import {
    ColorData,
    transformColorDataToJSON,
    transformJSONToColorData
} from './color-data';
import {
    Gradient,
    transformGradientToJSON,
    transformJSONToGradient
} from './gradient';


export const transformLayerFillToJSON = function (value: LayerFill): any {
    return {
        type: value.type,
        color: value.color && transformColorDataToJSON(value.color),
        gradient: value.gradient && transformGradientToJSON(value.gradient),
        blend_mode: value.blendMode && transformBlendModeEnumToJSON(value.blendMode)
    }
}

export const transformJSONToLayerFill = function (value: any): LayerFill {
    return {
        type: value.type,
        color: value.color && transformJSONToColorData(value.color),
        gradient: value.gradient && transformJSONToGradient(value.gradient),
        blendMode: value.blend_mode && transformJSONToBlendModeEnum(value.blend_mode)
    }
}

/**
 * 
 * @export
 * @interface LayerFill
 */
export interface LayerFill {
    /**
     * Type of the fill
     * @type {string}
     * @memberof LayerFill
     */
    type: 'color' | 'gradient';
    /**
     * 
     * @type {ColorData}
     * @memberof LayerFill
     */
    color?: ColorData;
    /**
     * 
     * @type {Gradient}
     * @memberof LayerFill
     */
    gradient?: Gradient;
    /**
     * 
     * @type {BlendModeEnum}
     * @memberof LayerFill
     */
    blendMode?: BlendModeEnum;
}


