/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    LayerFill,
    transformLayerFillToJSON,
    transformJSONToLayerFill
} from './layer-fill';


export const transformLayerBorderToJSON = function (value: LayerBorder): any {
    return {
        position: value.position,
        thickness: value.thickness,
        fill: value.fill && transformLayerFillToJSON(value.fill)
    }
}

export const transformJSONToLayerBorder = function (value: any): LayerBorder {
    return {
        position: value.position,
        thickness: value.thickness,
        fill: value.fill && transformJSONToLayerFill(value.fill)
    }
}

/**
 * 
 * @export
 * @interface LayerBorder
 */
export interface LayerBorder {
    /**
     * Position of the border
     * @type {string}
     * @memberof LayerBorder
     */
    position?: 'center' | 'inside' | 'outside';
    /**
     * Thickness of the border
     * @type {number}
     * @memberof LayerBorder
     */
    thickness?: number;
    /**
     * 
     * @type {LayerFill}
     * @memberof LayerBorder
     */
    fill?: LayerFill;
}


