/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformLayerTextStyleRangeToJSON = function (value: LayerTextStyleRange): any {
    return {
        location: value.location,
        length: value.length
    }
}

export const transformJSONToLayerTextStyleRange = function (value: any): LayerTextStyleRange {
    return {
        location: value.location,
        length: value.length
    }
}

/**
 * 
 * @export
 * @interface LayerTextStyleRange
 */
export interface LayerTextStyleRange {
    /**
     * Start of the range
     * @type {number}
     * @memberof LayerTextStyleRange
     */
    location?: number;
    /**
     * Length of the range
     * @type {number}
     * @memberof LayerTextStyleRange
     */
    length?: number;
}


