/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformLayerLayoutPaddingToJSON = function (value: LayerLayoutPadding): any {
    return {
        top: value.top,
        right: value.right,
        bottom: value.bottom,
        left: value.left
    }
}

export const transformJSONToLayerLayoutPadding = function (value: any): LayerLayoutPadding {
    return {
        top: value.top,
        right: value.right,
        bottom: value.bottom,
        left: value.left
    }
}

/**
 * Padding around the children
 * @export
 * @interface LayerLayoutPadding
 */
export interface LayerLayoutPadding {
    /**
     * 
     * @type {number}
     * @memberof LayerLayoutPadding
     */
    top?: number;
    /**
     * 
     * @type {number}
     * @memberof LayerLayoutPadding
     */
    right?: number;
    /**
     * 
     * @type {number}
     * @memberof LayerLayoutPadding
     */
    bottom?: number;
    /**
     * 
     * @type {number}
     * @memberof LayerLayoutPadding
     */
    left?: number;
}


