/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformLinkDestinationToJSON = function (value: LinkDestination): any {
    return {
        name: value.name,
        type: value.type
    }
}

export const transformJSONToLinkDestination = function (value: any): LinkDestination {
    return {
        name: value.name,
        type: value.type
    }
}

/**
 * 
 * @export
 * @interface LinkDestination
 */
export interface LinkDestination {
    /**
     * 
     * @type {string}
     * @memberof LinkDestination
     */
    name: string;
    /**
     * Type of the link (`component` or `previous`)
     * @type {string}
     * @memberof LinkDestination
     */
    type: 'component' | 'previous';
}


