/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformNotificationUpdateBodyToJSON = function (value: NotificationUpdateBody): any {
    return {
        is_read: value.isRead
    }
}

export const transformJSONToNotificationUpdateBody = function (value: any): NotificationUpdateBody {
    return {
        isRead: value.is_read
    }
}

/**
 * 
 * @export
 * @interface NotificationUpdateBody
 */
export interface NotificationUpdateBody {
    /**
     * New is_read status for notifications
     * @type {boolean}
     * @memberof NotificationUpdateBody
     */
    isRead: boolean;
}


