/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformNotificationTypeEnumToJSON = function (value: NotificationTypeEnum): any {
    return value;
}

export const transformJSONToNotificationTypeEnum = function (value: any): NotificationTypeEnum {
    return value;
}

/**
 * 
 * @export
 * @enum {string}
 */
export enum NotificationTypeEnum {
    WORKSPACE_PROJECT = 'workspace.project',
    WORKSPACE_STYLEGUIDE = 'workspace.styleguide',
    PROJECT_EXTENSION = 'project.extension',
    STYLEGUIDE_EXTENSION = 'styleguide.extension',
    USER_PROJECT_MEMBERSHIP = 'user.project_membership',
    USER_STYLEGUIDE_MEMBERSHIP = 'user.styleguide_membership',
    PROJECT_COMPONENT = 'project.component',
    STYLEGUIDE_COMPONENT = 'styleguide.component',
    PROJECT_COLOR = 'project.color',
    STYLEGUIDE_COLOR = 'styleguide.color',
    PROJECT_SCREEN_NOTE = 'project.screen.note',
    PROJECT_SCREEN_NOTE_COMMENT = 'project.screen.note.comment',
    PROJECT_SCREEN = 'project.screen',
    PROJECT_TEXT_STYLE = 'project.text_style',
    STYLEGUIDE_TEXT_STYLE = 'styleguide.text_style',
    PROJECT_SPACING_TOKEN = 'project.spacing_token',
    STYLEGUIDE_SPACING_TOKEN = 'styleguide.spacing_token',
    PROJECT_JIRA_ATTACHMENT = 'project.jira_attachment',
    PROJECT_SCREEN_SECTION_JIRA_ATTACHMENT = 'project.screen_section.jira_attachment',
    PROJECT_SCREEN_JIRA_ATTACHMENT = 'project.screen.jira_attachment',
    WORKSPACE_ORGANIZATION_MEMBER = 'workspace.organization.member',
    PROJECT_SLACK_INTEGRATION = 'project.slack_integration',
    STYLEGUIDE_SLACK_INTEGRATION = 'styleguide.slack_integration',
    PROJECT_MEMBER = 'project.member',
    STYLEGUIDE_MEMBER = 'styleguide.member',
    PROJECT_FLOW_BOARD = 'project.flow_board'
}


