/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformOrganizationMemberUpdateBodyToJSON = function (value: OrganizationMemberUpdateBody): any {
    return {
        tags: value.tags && [...value.tags],
        role: value.role,
        restricted: value.restricted
    }
}

export const transformJSONToOrganizationMemberUpdateBody = function (value: any): OrganizationMemberUpdateBody {
    return {
        tags: value.tags && new Set(value.tags),
        role: value.role,
        restricted: value.restricted
    }
}

/**
 * 
 * @export
 * @interface OrganizationMemberUpdateBody
 */
export interface OrganizationMemberUpdateBody {
    /**
     * Tags of the user in the organization
     * @type {Set<string>}
     * @memberof OrganizationMemberUpdateBody
     */
    tags?: Set<string>;
    /**
     * The role of the user in the organization  ☝️Note that the Developer role maps to `member` and the Reviewer role maps to `alien` in the API. 
     * @type {string}
     * @memberof OrganizationMemberUpdateBody
     */
    role?: 'admin' | 'editor' | 'member' | 'alien';
    /**
     * Whether the user\'s membership is restricted to only the
     * @type {boolean}
     * @memberof OrganizationMemberUpdateBody
     */
    restricted?: boolean;
}


