/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformOrganizationMemberInviteBodyToJSON = function (value: OrganizationMemberInviteBody): any {
    return {
        handle: value.handle,
        tags: value.tags && [...value.tags],
        role: value.role,
        restricted: value.restricted
    }
}

export const transformJSONToOrganizationMemberInviteBody = function (value: any): OrganizationMemberInviteBody {
    return {
        handle: value.handle,
        tags: value.tags && new Set(value.tags),
        role: value.role,
        restricted: value.restricted
    }
}

/**
 * 
 * @export
 * @interface OrganizationMemberInviteBody
 */
export interface OrganizationMemberInviteBody {
    /**
     * Email, username or unique identifier of the user
     * @type {string}
     * @memberof OrganizationMemberInviteBody
     */
    handle: string;
    /**
     * Tags of the user in the organization
     * @type {Set<string>}
     * @memberof OrganizationMemberInviteBody
     */
    tags?: Set<string>;
    /**
     * The role of the user in the organization  ☝️Note that the Developer role maps to `member` and the Reviewer role maps to `alien` in the API. 
     * @type {string}
     * @memberof OrganizationMemberInviteBody
     */
    role: 'admin' | 'editor' | 'member' | 'alien';
    /**
     * Whether the user\'s membership is restricted to only the projects that they are member of
     * @type {boolean}
     * @memberof OrganizationMemberInviteBody
     */
    restricted: boolean;
}


