/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformOrganizationSummaryToJSON = function (value: OrganizationSummary): any {
    return {
        id: value.id,
        name: value.name,
        logo: value.logo
    }
}

export const transformJSONToOrganizationSummary = function (value: any): OrganizationSummary {
    return {
        id: value.id,
        name: value.name,
        logo: value.logo
    }
}

/**
 * 
 * @export
 * @interface OrganizationSummary
 */
export interface OrganizationSummary {
    /**
     * Organization\'s unique id
     * @type {string}
     * @memberof OrganizationSummary
     */
    id: string;
    /**
     * Name of the user
     * @type {string}
     * @memberof OrganizationSummary
     */
    name: string;
    /**
     * URL of the organization\'s logo
     * @type {string}
     * @memberof OrganizationSummary
     */
    logo?: string;
}


