/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformPageToJSON = function (value: Page): any {
    return {
        id: value.id,
        name: value.name,
        type: value.type,
        description: value.description,
        componentSections: value.componentSections
    }
}

export const transformJSONToPage = function (value: any): Page {
    return {
        id: value.id,
        name: value.name,
        type: value.type,
        description: value.description,
        componentSections: value.componentSections
    }
}

/**
 * 
 * @export
 * @interface Page
 */
export interface Page {
    /**
     * The unique id of the page
     * @type {string}
     * @memberof Page
     */
    id: string;
    /**
     * The name of the page
     * @type {string}
     * @memberof Page
     */
    name: string;
    /**
     * The type of the page
     * @type {string}
     * @memberof Page
     */
    type: string;
    /**
     * The description of the page
     * @type {string}
     * @memberof Page
     */
    description?: string;
    /**
     * Array of component section IDs
     * @type {Array<string>}
     * @memberof Page
     */
    componentSections: Array<string>;
}


