/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformProjectScreenDeletedEventResourceToJSON = function (value: ProjectScreenDeletedEventResource): any {
    return {
        id: value.id,
        type: value.type
    }
}

export const transformJSONToProjectScreenDeletedEventResource = function (value: any): ProjectScreenDeletedEventResource {
    return {
        id: value.id,
        type: value.type
    }
}

/**
 * 
 * @export
 * @interface ProjectScreenDeletedEventResource
 */
export interface ProjectScreenDeletedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenDeletedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenDeletedEventResource
     */
    type: 'Screen';
}


