/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectComponentDeletedEventResource,
    transformProjectComponentDeletedEventResourceToJSON,
    transformJSONToProjectComponentDeletedEventResource
} from './project-component-deleted-event-resource';
import {
    ProjectComponentEventContext,
    transformProjectComponentEventContextToJSON,
    transformJSONToProjectComponentEventContext
} from './project-component-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectComponentDeletedEventToJSON = function (value: ProjectComponentDeletedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectComponentDeletedEventResourceToJSON(value.resource),
        context: transformProjectComponentEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectComponentDeletedEvent = function (value: any): ProjectComponentDeletedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectComponentDeletedEventResource(value.resource),
        context: transformJSONToProjectComponentEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectComponentDeletedEvent
 */
export interface ProjectComponentDeletedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentDeletedEvent
     */
    event: 'project.component';
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentDeletedEvent
     */
    action: 'deleted';
    /**
     * 
     * @type {number}
     * @memberof ProjectComponentDeletedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectComponentDeletedEventResource}
     * @memberof ProjectComponentDeletedEvent
     */
    resource: ProjectComponentDeletedEventResource;
    /**
     * 
     * @type {ProjectComponentEventContext}
     * @memberof ProjectComponentDeletedEvent
     */
    context: ProjectComponentEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectComponentDeletedEvent
     */
    actor: WebhookEventActor;
}


