/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformProjectMemberInviteBodyToJSON = function (value: ProjectMemberInviteBody): any {
    return {
        handle: value.handle
    }
}

export const transformJSONToProjectMemberInviteBody = function (value: any): ProjectMemberInviteBody {
    return {
        handle: value.handle
    }
}

/**
 * 
 * @export
 * @interface ProjectMemberInviteBody
 */
export interface ProjectMemberInviteBody {
    /**
     * Email, username or unique identifier of the user  Can also be `\"me\"` for joining the project as the current user 
     * @type {string}
     * @memberof ProjectMemberInviteBody
     */
    handle: string;
}


