/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectScreenCreatedEventResource,
    transformProjectScreenCreatedEventResourceToJSON,
    transformJSONToProjectScreenCreatedEventResource
} from './project-screen-created-event-resource';
import {
    ProjectScreenEventContext,
    transformProjectScreenEventContextToJSON,
    transformJSONToProjectScreenEventContext
} from './project-screen-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectScreenUpdatedEventToJSON = function (value: ProjectScreenUpdatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectScreenCreatedEventResourceToJSON(value.resource),
        context: transformProjectScreenEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectScreenUpdatedEvent = function (value: any): ProjectScreenUpdatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectScreenCreatedEventResource(value.resource),
        context: transformJSONToProjectScreenEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectScreenUpdatedEvent
 */
export interface ProjectScreenUpdatedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenUpdatedEvent
     */
    event: 'project.screen';
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenUpdatedEvent
     */
    action: 'updated';
    /**
     * 
     * @type {number}
     * @memberof ProjectScreenUpdatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectScreenCreatedEventResource}
     * @memberof ProjectScreenUpdatedEvent
     */
    resource: ProjectScreenCreatedEventResource;
    /**
     * 
     * @type {ProjectScreenEventContext}
     * @memberof ProjectScreenUpdatedEvent
     */
    context: ProjectScreenEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectScreenUpdatedEvent
     */
    actor: WebhookEventActor;
}


