/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectNoteCreatedEvent,
    transformProjectNoteCreatedEventToJSON,
    transformJSONToProjectNoteCreatedEvent
} from './project-note-created-event';
import {
    ProjectNoteCreatedEventResource,
    transformProjectNoteCreatedEventResourceToJSON,
    transformJSONToProjectNoteCreatedEventResource
} from './project-note-created-event-resource';
import {
    ProjectNoteDeletedEvent,
    transformProjectNoteDeletedEventToJSON,
    transformJSONToProjectNoteDeletedEvent
} from './project-note-deleted-event';
import {
    ProjectNoteEventContext,
    transformProjectNoteEventContextToJSON,
    transformJSONToProjectNoteEventContext
} from './project-note-event-context';
import {
    ProjectNoteUpdatedEvent,
    transformProjectNoteUpdatedEventToJSON,
    transformJSONToProjectNoteUpdatedEvent
} from './project-note-updated-event';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformJSONToProjectNoteEvent = function (value: any): ProjectNoteEvent {
    switch (value.action) {
        case 'created':
            return transformJSONToProjectNoteCreatedEvent(value);
        case 'deleted':
            return transformJSONToProjectNoteDeletedEvent(value);
        case 'updated':
            return transformJSONToProjectNoteUpdatedEvent(value);
        default:
            throw new Error(`No variant of ProjectNoteEvent exists with 'action=${ value.action }'`);
    }
}

export const transformProjectNoteEventToJSON = function (value: ProjectNoteEvent): any {
    switch (value.action) {
        case 'created':
            return transformProjectNoteCreatedEventToJSON(value);
        case 'deleted':
            return transformProjectNoteDeletedEventToJSON(value);
        case 'updated':
            return transformProjectNoteUpdatedEventToJSON(value);
    }
}

/**
 * @type ProjectNoteEvent
 * This event is used to notify webhooks about changes related to a notes in Zeplin projects.
 * @export
 */
export type ProjectNoteEvent = ProjectNoteCreatedEvent | ProjectNoteDeletedEvent | ProjectNoteUpdatedEvent;


