/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectScreenDeletedEventContext,
    transformProjectScreenDeletedEventContextToJSON,
    transformJSONToProjectScreenDeletedEventContext
} from './project-screen-deleted-event-context';
import {
    ProjectScreenDeletedEventResource,
    transformProjectScreenDeletedEventResourceToJSON,
    transformJSONToProjectScreenDeletedEventResource
} from './project-screen-deleted-event-resource';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectScreenDeletedEventToJSON = function (value: ProjectScreenDeletedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectScreenDeletedEventResourceToJSON(value.resource),
        context: transformProjectScreenDeletedEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectScreenDeletedEvent = function (value: any): ProjectScreenDeletedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectScreenDeletedEventResource(value.resource),
        context: transformJSONToProjectScreenDeletedEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectScreenDeletedEvent
 */
export interface ProjectScreenDeletedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenDeletedEvent
     */
    event: 'project.screen';
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenDeletedEvent
     */
    action: 'deleted';
    /**
     * 
     * @type {number}
     * @memberof ProjectScreenDeletedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectScreenDeletedEventResource}
     * @memberof ProjectScreenDeletedEvent
     */
    resource: ProjectScreenDeletedEventResource;
    /**
     * 
     * @type {ProjectScreenDeletedEventContext}
     * @memberof ProjectScreenDeletedEvent
     */
    context: ProjectScreenDeletedEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectScreenDeletedEvent
     */
    actor: WebhookEventActor;
}


