/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformProjectNoteDeletedEventResourceToJSON = function (value: ProjectNoteDeletedEventResource): any {
    return {
        id: value.id,
        type: value.type
    }
}

export const transformJSONToProjectNoteDeletedEventResource = function (value: any): ProjectNoteDeletedEventResource {
    return {
        id: value.id,
        type: value.type
    }
}

/**
 * 
 * @export
 * @interface ProjectNoteDeletedEventResource
 */
export interface ProjectNoteDeletedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteDeletedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteDeletedEventResource
     */
    type: 'ScreenNote';
}


