/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectNoteCommentReactionDeletedEventResource,
    transformProjectNoteCommentReactionDeletedEventResourceToJSON,
    transformJSONToProjectNoteCommentReactionDeletedEventResource
} from './project-note-comment-reaction-deleted-event-resource';
import {
    ProjectNoteCommentReactionEventContext,
    transformProjectNoteCommentReactionEventContextToJSON,
    transformJSONToProjectNoteCommentReactionEventContext
} from './project-note-comment-reaction-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectNoteCommentReactionDeletedEventToJSON = function (value: ProjectNoteCommentReactionDeletedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectNoteCommentReactionDeletedEventResourceToJSON(value.resource),
        context: transformProjectNoteCommentReactionEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectNoteCommentReactionDeletedEvent = function (value: any): ProjectNoteCommentReactionDeletedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectNoteCommentReactionDeletedEventResource(value.resource),
        context: transformJSONToProjectNoteCommentReactionEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectNoteCommentReactionDeletedEvent
 */
export interface ProjectNoteCommentReactionDeletedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteCommentReactionDeletedEvent
     */
    event: 'project.note.comment.reaction';
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteCommentReactionDeletedEvent
     */
    action: 'deleted';
    /**
     * 
     * @type {number}
     * @memberof ProjectNoteCommentReactionDeletedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectNoteCommentReactionDeletedEventResource}
     * @memberof ProjectNoteCommentReactionDeletedEvent
     */
    resource: ProjectNoteCommentReactionDeletedEventResource;
    /**
     * 
     * @type {ProjectNoteCommentReactionEventContext}
     * @memberof ProjectNoteCommentReactionDeletedEvent
     */
    context: ProjectNoteCommentReactionEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectNoteCommentReactionDeletedEvent
     */
    actor: WebhookEventActor;
}


