/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformProjectNoteCommentReactionDeletedEventResourceToJSON = function (value: ProjectNoteCommentReactionDeletedEventResource): any {
    return {
        id: value.id,
        type: value.type
    }
}

export const transformJSONToProjectNoteCommentReactionDeletedEventResource = function (value: any): ProjectNoteCommentReactionDeletedEventResource {
    return {
        id: value.id,
        type: value.type
    }
}

/**
 * 
 * @export
 * @interface ProjectNoteCommentReactionDeletedEventResource
 */
export interface ProjectNoteCommentReactionDeletedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteCommentReactionDeletedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteCommentReactionDeletedEventResource
     */
    type: 'Reaction';
}


