/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Component,
    transformComponentToJSON,
    transformJSONToComponent
} from './component';


export const transformProjectComponentCreatedEventResourceToJSON = function (value: ProjectComponentCreatedEventResource): any {
    return {
        id: value.id,
        type: value.type,
        data: transformComponentToJSON(value.data)
    }
}

export const transformJSONToProjectComponentCreatedEventResource = function (value: any): ProjectComponentCreatedEventResource {
    return {
        id: value.id,
        type: value.type,
        data: transformJSONToComponent(value.data)
    }
}

/**
 * 
 * @export
 * @interface ProjectComponentCreatedEventResource
 */
export interface ProjectComponentCreatedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentCreatedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentCreatedEventResource
     */
    type: 'Component';
    /**
     * 
     * @type {Component}
     * @memberof ProjectComponentCreatedEventResource
     */
    data: Component;
}


