/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectNoteCommentCreatedEventResource,
    transformProjectNoteCommentCreatedEventResourceToJSON,
    transformJSONToProjectNoteCommentCreatedEventResource
} from './project-note-comment-created-event-resource';
import {
    ProjectNoteCommentEventContext,
    transformProjectNoteCommentEventContextToJSON,
    transformJSONToProjectNoteCommentEventContext
} from './project-note-comment-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectNoteCommentCreatedEventToJSON = function (value: ProjectNoteCommentCreatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectNoteCommentCreatedEventResourceToJSON(value.resource),
        context: transformProjectNoteCommentEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectNoteCommentCreatedEvent = function (value: any): ProjectNoteCommentCreatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectNoteCommentCreatedEventResource(value.resource),
        context: transformJSONToProjectNoteCommentEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectNoteCommentCreatedEvent
 */
export interface ProjectNoteCommentCreatedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteCommentCreatedEvent
     */
    event: 'project.note.comment';
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteCommentCreatedEvent
     */
    action: 'created';
    /**
     * 
     * @type {number}
     * @memberof ProjectNoteCommentCreatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectNoteCommentCreatedEventResource}
     * @memberof ProjectNoteCommentCreatedEvent
     */
    resource: ProjectNoteCommentCreatedEventResource;
    /**
     * 
     * @type {ProjectNoteCommentEventContext}
     * @memberof ProjectNoteCommentCreatedEvent
     */
    context: ProjectNoteCommentEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectNoteCommentCreatedEvent
     */
    actor: WebhookEventActor;
}


