/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectNoteDeletedEventResource,
    transformProjectNoteDeletedEventResourceToJSON,
    transformJSONToProjectNoteDeletedEventResource
} from './project-note-deleted-event-resource';
import {
    ProjectNoteEventContext,
    transformProjectNoteEventContextToJSON,
    transformJSONToProjectNoteEventContext
} from './project-note-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectNoteDeletedEventToJSON = function (value: ProjectNoteDeletedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectNoteDeletedEventResourceToJSON(value.resource),
        context: transformProjectNoteEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectNoteDeletedEvent = function (value: any): ProjectNoteDeletedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectNoteDeletedEventResource(value.resource),
        context: transformJSONToProjectNoteEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectNoteDeletedEvent
 */
export interface ProjectNoteDeletedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteDeletedEvent
     */
    event: 'project.note';
    /**
     * 
     * @type {string}
     * @memberof ProjectNoteDeletedEvent
     */
    action: 'deleted';
    /**
     * 
     * @type {number}
     * @memberof ProjectNoteDeletedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectNoteDeletedEventResource}
     * @memberof ProjectNoteDeletedEvent
     */
    resource: ProjectNoteDeletedEventResource;
    /**
     * 
     * @type {ProjectNoteEventContext}
     * @memberof ProjectNoteDeletedEvent
     */
    context: ProjectNoteEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectNoteDeletedEvent
     */
    actor: WebhookEventActor;
}


