/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectComponentCreatedEventResource,
    transformProjectComponentCreatedEventResourceToJSON,
    transformJSONToProjectComponentCreatedEventResource
} from './project-component-created-event-resource';
import {
    ProjectComponentEventContext,
    transformProjectComponentEventContextToJSON,
    transformJSONToProjectComponentEventContext
} from './project-component-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectComponentVersionCreatedEventToJSON = function (value: ProjectComponentVersionCreatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectComponentCreatedEventResourceToJSON(value.resource),
        context: transformProjectComponentEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectComponentVersionCreatedEvent = function (value: any): ProjectComponentVersionCreatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectComponentCreatedEventResource(value.resource),
        context: transformJSONToProjectComponentEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectComponentVersionCreatedEvent
 */
export interface ProjectComponentVersionCreatedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentVersionCreatedEvent
     */
    event: 'project.component';
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentVersionCreatedEvent
     */
    action: 'version_created';
    /**
     * 
     * @type {number}
     * @memberof ProjectComponentVersionCreatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectComponentCreatedEventResource}
     * @memberof ProjectComponentVersionCreatedEvent
     */
    resource: ProjectComponentCreatedEventResource;
    /**
     * 
     * @type {ProjectComponentEventContext}
     * @memberof ProjectComponentVersionCreatedEvent
     */
    context: ProjectComponentEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectComponentVersionCreatedEvent
     */
    actor: WebhookEventActor;
}


