/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Project,
    transformProjectToJSON,
    transformJSONToProject
} from './project';


export const transformProjectComponentDeletedEventContextToJSON = function (value: ProjectComponentDeletedEventContext): any {
    return {
        project: transformProjectToJSON(value.project)
    }
}

export const transformJSONToProjectComponentDeletedEventContext = function (value: any): ProjectComponentDeletedEventContext {
    return {
        project: transformJSONToProject(value.project)
    }
}

/**
 * 
 * @export
 * @interface ProjectComponentDeletedEventContext
 */
export interface ProjectComponentDeletedEventContext {
    /**
     * 
     * @type {Project}
     * @memberof ProjectComponentDeletedEventContext
     */
    project: Project;
}


