/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectTextStyleDeletedEventResource,
    transformProjectTextStyleDeletedEventResourceToJSON,
    transformJSONToProjectTextStyleDeletedEventResource
} from './project-text-style-deleted-event-resource';
import {
    ProjectTextStyleEventContext,
    transformProjectTextStyleEventContextToJSON,
    transformJSONToProjectTextStyleEventContext
} from './project-text-style-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectTextStyleDeletedEventToJSON = function (value: ProjectTextStyleDeletedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectTextStyleDeletedEventResourceToJSON(value.resource),
        context: transformProjectTextStyleEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectTextStyleDeletedEvent = function (value: any): ProjectTextStyleDeletedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectTextStyleDeletedEventResource(value.resource),
        context: transformJSONToProjectTextStyleEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectTextStyleDeletedEvent
 */
export interface ProjectTextStyleDeletedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectTextStyleDeletedEvent
     */
    event: 'project.text_style';
    /**
     * 
     * @type {string}
     * @memberof ProjectTextStyleDeletedEvent
     */
    action: 'deleted';
    /**
     * 
     * @type {number}
     * @memberof ProjectTextStyleDeletedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectTextStyleDeletedEventResource}
     * @memberof ProjectTextStyleDeletedEvent
     */
    resource: ProjectTextStyleDeletedEventResource;
    /**
     * 
     * @type {ProjectTextStyleEventContext}
     * @memberof ProjectTextStyleDeletedEvent
     */
    context: ProjectTextStyleEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectTextStyleDeletedEvent
     */
    actor: WebhookEventActor;
}


