/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformProjectComponentDeletedEventResourceToJSON = function (value: ProjectComponentDeletedEventResource): any {
    return {
        id: value.id,
        type: value.type
    }
}

export const transformJSONToProjectComponentDeletedEventResource = function (value: any): ProjectComponentDeletedEventResource {
    return {
        id: value.id,
        type: value.type
    }
}

/**
 * 
 * @export
 * @interface ProjectComponentDeletedEventResource
 */
export interface ProjectComponentDeletedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentDeletedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectComponentDeletedEventResource
     */
    type: 'Component';
}


