/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ComponentVersionSummary,
    transformComponentVersionSummaryToJSON,
    transformJSONToComponentVersionSummary
} from './component-version-summary';
import {
    Project,
    transformProjectToJSON,
    transformJSONToProject
} from './project';


export const transformProjectComponentEventContextToJSON = function (value: ProjectComponentEventContext): any {
    return {
        project: transformProjectToJSON(value.project),
        version: transformComponentVersionSummaryToJSON(value.version)
    }
}

export const transformJSONToProjectComponentEventContext = function (value: any): ProjectComponentEventContext {
    return {
        project: transformJSONToProject(value.project),
        version: transformJSONToComponentVersionSummary(value.version)
    }
}

/**
 * 
 * @export
 * @interface ProjectComponentEventContext
 */
export interface ProjectComponentEventContext {
    /**
     * 
     * @type {Project}
     * @memberof ProjectComponentEventContext
     */
    project: Project;
    /**
     * 
     * @type {ComponentVersionSummary}
     * @memberof ProjectComponentEventContext
     */
    version: ComponentVersionSummary;
}


