/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectScreenVersionCreatedEventResource,
    transformProjectScreenVersionCreatedEventResourceToJSON,
    transformJSONToProjectScreenVersionCreatedEventResource
} from './project-screen-version-created-event-resource';
import {
    ProjectScreenVersionEventContext,
    transformProjectScreenVersionEventContextToJSON,
    transformJSONToProjectScreenVersionEventContext
} from './project-screen-version-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectScreenVersionCreatedEventToJSON = function (value: ProjectScreenVersionCreatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectScreenVersionCreatedEventResourceToJSON(value.resource),
        context: transformProjectScreenVersionEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectScreenVersionCreatedEvent = function (value: any): ProjectScreenVersionCreatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectScreenVersionCreatedEventResource(value.resource),
        context: transformJSONToProjectScreenVersionEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectScreenVersionCreatedEvent
 */
export interface ProjectScreenVersionCreatedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenVersionCreatedEvent
     */
    event: 'project.screen.version';
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenVersionCreatedEvent
     */
    action: 'created';
    /**
     * 
     * @type {number}
     * @memberof ProjectScreenVersionCreatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectScreenVersionCreatedEventResource}
     * @memberof ProjectScreenVersionCreatedEvent
     */
    resource: ProjectScreenVersionCreatedEventResource;
    /**
     * 
     * @type {ProjectScreenVersionEventContext}
     * @memberof ProjectScreenVersionCreatedEvent
     */
    context: ProjectScreenVersionEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectScreenVersionCreatedEvent
     */
    actor: WebhookEventActor;
}


