/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Project,
    transformProjectToJSON,
    transformJSONToProject
} from './project';


export const transformProjectSpacingTokenEventContextToJSON = function (value: ProjectSpacingTokenEventContext): any {
    return {
        project: transformProjectToJSON(value.project)
    }
}

export const transformJSONToProjectSpacingTokenEventContext = function (value: any): ProjectSpacingTokenEventContext {
    return {
        project: transformJSONToProject(value.project)
    }
}

/**
 * 
 * @export
 * @interface ProjectSpacingTokenEventContext
 */
export interface ProjectSpacingTokenEventContext {
    /**
     * 
     * @type {Project}
     * @memberof ProjectSpacingTokenEventContext
     */
    project: Project;
}


