/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectSpacingTokenCreatedEventResource,
    transformProjectSpacingTokenCreatedEventResourceToJSON,
    transformJSONToProjectSpacingTokenCreatedEventResource
} from './project-spacing-token-created-event-resource';
import {
    ProjectSpacingTokenEventContext,
    transformProjectSpacingTokenEventContextToJSON,
    transformJSONToProjectSpacingTokenEventContext
} from './project-spacing-token-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformProjectSpacingTokenCreatedEventToJSON = function (value: ProjectSpacingTokenCreatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectSpacingTokenCreatedEventResourceToJSON(value.resource),
        context: transformProjectSpacingTokenEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToProjectSpacingTokenCreatedEvent = function (value: any): ProjectSpacingTokenCreatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectSpacingTokenCreatedEventResource(value.resource),
        context: transformJSONToProjectSpacingTokenEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface ProjectSpacingTokenCreatedEvent
 */
export interface ProjectSpacingTokenCreatedEvent {
    /**
     * 
     * @type {string}
     * @memberof ProjectSpacingTokenCreatedEvent
     */
    event: 'project.spacing_token';
    /**
     * 
     * @type {string}
     * @memberof ProjectSpacingTokenCreatedEvent
     */
    action: 'created';
    /**
     * 
     * @type {number}
     * @memberof ProjectSpacingTokenCreatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectSpacingTokenCreatedEventResource}
     * @memberof ProjectSpacingTokenCreatedEvent
     */
    resource: ProjectSpacingTokenCreatedEventResource;
    /**
     * 
     * @type {ProjectSpacingTokenEventContext}
     * @memberof ProjectSpacingTokenCreatedEvent
     */
    context: ProjectSpacingTokenEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof ProjectSpacingTokenCreatedEvent
     */
    actor: WebhookEventActor;
}


