/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    SpacingToken,
    transformSpacingTokenToJSON,
    transformJSONToSpacingToken
} from './spacing-token';


export const transformProjectSpacingTokenCreatedEventResourceToJSON = function (value: ProjectSpacingTokenCreatedEventResource): any {
    return {
        id: value.id,
        type: value.type,
        data: transformSpacingTokenToJSON(value.data)
    }
}

export const transformJSONToProjectSpacingTokenCreatedEventResource = function (value: any): ProjectSpacingTokenCreatedEventResource {
    return {
        id: value.id,
        type: value.type,
        data: transformJSONToSpacingToken(value.data)
    }
}

/**
 * 
 * @export
 * @interface ProjectSpacingTokenCreatedEventResource
 */
export interface ProjectSpacingTokenCreatedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectSpacingTokenCreatedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSpacingTokenCreatedEventResource
     */
    type: 'SpacingToken';
    /**
     * 
     * @type {SpacingToken}
     * @memberof ProjectSpacingTokenCreatedEventResource
     */
    data: SpacingToken;
}


