/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Screen,
    transformScreenToJSON,
    transformJSONToScreen
} from './screen';


export const transformProjectScreenCreatedEventResourceToJSON = function (value: ProjectScreenCreatedEventResource): any {
    return {
        id: value.id,
        type: value.type,
        data: transformScreenToJSON(value.data)
    }
}

export const transformJSONToProjectScreenCreatedEventResource = function (value: any): ProjectScreenCreatedEventResource {
    return {
        id: value.id,
        type: value.type,
        data: transformJSONToScreen(value.data)
    }
}

/**
 * 
 * @export
 * @interface ProjectScreenCreatedEventResource
 */
export interface ProjectScreenCreatedEventResource {
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenCreatedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectScreenCreatedEventResource
     */
    type: 'Screen';
    /**
     * 
     * @type {Screen}
     * @memberof ProjectScreenCreatedEventResource
     */
    data: Screen;
}


