/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectTextStyleCreatedEvent,
    transformProjectTextStyleCreatedEventToJSON,
    transformJSONToProjectTextStyleCreatedEvent
} from './project-text-style-created-event';
import {
    ProjectTextStyleCreatedEventResource,
    transformProjectTextStyleCreatedEventResourceToJSON,
    transformJSONToProjectTextStyleCreatedEventResource
} from './project-text-style-created-event-resource';
import {
    ProjectTextStyleDeletedEvent,
    transformProjectTextStyleDeletedEventToJSON,
    transformJSONToProjectTextStyleDeletedEvent
} from './project-text-style-deleted-event';
import {
    ProjectTextStyleEventContext,
    transformProjectTextStyleEventContextToJSON,
    transformJSONToProjectTextStyleEventContext
} from './project-text-style-event-context';
import {
    ProjectTextStyleUpdatedEvent,
    transformProjectTextStyleUpdatedEventToJSON,
    transformJSONToProjectTextStyleUpdatedEvent
} from './project-text-style-updated-event';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformJSONToProjectTextStyleEvent = function (value: any): ProjectTextStyleEvent {
    switch (value.action) {
        case 'created':
            return transformJSONToProjectTextStyleCreatedEvent(value);
        case 'deleted':
            return transformJSONToProjectTextStyleDeletedEvent(value);
        case 'updated':
            return transformJSONToProjectTextStyleUpdatedEvent(value);
        default:
            throw new Error(`No variant of ProjectTextStyleEvent exists with 'action=${ value.action }'`);
    }
}

export const transformProjectTextStyleEventToJSON = function (value: ProjectTextStyleEvent): any {
    switch (value.action) {
        case 'created':
            return transformProjectTextStyleCreatedEventToJSON(value);
        case 'deleted':
            return transformProjectTextStyleDeletedEventToJSON(value);
        case 'updated':
            return transformProjectTextStyleUpdatedEventToJSON(value);
    }
}

/**
 * @type ProjectTextStyleEvent
 * This event is used to notify webhooks about changes related to a text styles in the local styleguide of Zeplin projects.
 * @export
 */
export type ProjectTextStyleEvent = ProjectTextStyleCreatedEvent | ProjectTextStyleDeletedEvent | ProjectTextStyleUpdatedEvent;


