/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    User,
    transformUserToJSON,
    transformJSONToUser
} from './user';


export const transformReactionToJSON = function (value: Reaction): any {
    return {
        id: value.id,
        short_code: value.shortCode,
        unicode: value.unicode,
        users: value.users.map(transformUserToJSON)
    }
}

export const transformJSONToReaction = function (value: any): Reaction {
    return {
        id: value.id,
        shortCode: value.short_code,
        unicode: value.unicode,
        users: value.users.map(transformJSONToUser)
    }
}

/**
 * 
 * @export
 * @interface Reaction
 */
export interface Reaction {
    /**
     * Unique id of the reaction
     * @type {string}
     * @memberof Reaction
     */
    id: string;
    /**
     * Type of the reaction (e.g., thumbsup, eyes, etc.)
     * @type {string}
     * @memberof Reaction
     */
    shortCode: string;
    /**
     * Unicode representation of the reaction
     * @type {string}
     * @memberof Reaction
     */
    unicode?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof Reaction
     */
    users: Array<User>;
}


