/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ScreenNoteColorNameEnum,
    transformScreenNoteColorNameEnumToJSON,
    transformJSONToScreenNoteColorNameEnum
} from './screen-note-color-name-enum';
import {
    ScreenNotePosition,
    transformScreenNotePositionToJSON,
    transformJSONToScreenNotePosition
} from './screen-note-position';
import {
    ScreenNoteStatusEnum,
    transformScreenNoteStatusEnumToJSON,
    transformJSONToScreenNoteStatusEnum
} from './screen-note-status-enum';


export const transformScreenNoteUpdateBodyToJSON = function (value: ScreenNoteUpdateBody): any {
    return {
        status: value.status && transformScreenNoteStatusEnumToJSON(value.status),
        position: value.position && transformScreenNotePositionToJSON(value.position),
        color: value.color && transformScreenNoteColorNameEnumToJSON(value.color)
    }
}

export const transformJSONToScreenNoteUpdateBody = function (value: any): ScreenNoteUpdateBody {
    return {
        status: value.status && transformJSONToScreenNoteStatusEnum(value.status),
        position: value.position && transformJSONToScreenNotePosition(value.position),
        color: value.color && transformJSONToScreenNoteColorNameEnum(value.color)
    }
}

/**
 * 
 * @export
 * @interface ScreenNoteUpdateBody
 */
export interface ScreenNoteUpdateBody {
    /**
     * 
     * @type {ScreenNoteStatusEnum}
     * @memberof ScreenNoteUpdateBody
     */
    status?: ScreenNoteStatusEnum;
    /**
     * 
     * @type {ScreenNotePosition}
     * @memberof ScreenNoteUpdateBody
     */
    position?: ScreenNotePosition;
    /**
     * 
     * @type {ScreenNoteColorNameEnum}
     * @memberof ScreenNoteUpdateBody
     */
    color?: ScreenNoteColorNameEnum;
}


