/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ScreenAnnotationNoteType,
    transformScreenAnnotationNoteTypeToJSON,
    transformJSONToScreenAnnotationNoteType
} from './screen-annotation-note-type';
import {
    ScreenAnnotationPosition,
    transformScreenAnnotationPositionToJSON,
    transformJSONToScreenAnnotationPosition
} from './screen-annotation-position';
import {
    User,
    transformUserToJSON,
    transformJSONToUser
} from './user';


export const transformScreenAnnotationToJSON = function (value: ScreenAnnotation): any {
    return {
        id: value.id,
        content: value.content,
        type: transformScreenAnnotationNoteTypeToJSON(value.type),
        position: transformScreenAnnotationPositionToJSON(value.position),
        creator: transformUserToJSON(value.creator),
        updated_by: value.updatedBy && transformUserToJSON(value.updatedBy),
        updated: value.updated,
        created: value.created
    }
}

export const transformJSONToScreenAnnotation = function (value: any): ScreenAnnotation {
    return {
        id: value.id,
        content: value.content,
        type: transformJSONToScreenAnnotationNoteType(value.type),
        position: transformJSONToScreenAnnotationPosition(value.position),
        creator: transformJSONToUser(value.creator),
        updatedBy: value.updated_by && transformJSONToUser(value.updated_by),
        updated: value.updated,
        created: value.created
    }
}

/**
 * 
 * @export
 * @interface ScreenAnnotation
 */
export interface ScreenAnnotation {
    /**
     * The unique id of the annotation
     * @type {string}
     * @memberof ScreenAnnotation
     */
    id: string;
    /**
     * The text of the annotation
     * @type {string}
     * @memberof ScreenAnnotation
     */
    content: string;
    /**
     * 
     * @type {ScreenAnnotationNoteType}
     * @memberof ScreenAnnotation
     */
    type: ScreenAnnotationNoteType;
    /**
     * 
     * @type {ScreenAnnotationPosition}
     * @memberof ScreenAnnotation
     */
    position: ScreenAnnotationPosition;
    /**
     * 
     * @type {User}
     * @memberof ScreenAnnotation
     */
    creator: User;
    /**
     * 
     * @type {User}
     * @memberof ScreenAnnotation
     */
    updatedBy?: User;
    /**
     * The unix timestamp when the annotation was last updated
     * @type {number}
     * @memberof ScreenAnnotation
     */
    updated: number;
    /**
     * The unix timestamp when the annotation was created
     * @type {number}
     * @memberof ScreenAnnotation
     */
    created: number;
}


