/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ScreenVariantGroupReference,
    transformScreenVariantGroupReferenceToJSON,
    transformJSONToScreenVariantGroupReference
} from './screen-variant-group-reference';


export const transformScreenVariantToJSON = function (value: ScreenVariant): any {
    return {
        value: value.value,
        group: transformScreenVariantGroupReferenceToJSON(value.group)
    }
}

export const transformJSONToScreenVariant = function (value: any): ScreenVariant {
    return {
        value: value.value,
        group: transformJSONToScreenVariantGroupReference(value.group)
    }
}

/**
 * 
 * @export
 * @interface ScreenVariant
 */
export interface ScreenVariant {
    /**
     * Value for this variant of the screen
     * @type {string}
     * @memberof ScreenVariant
     */
    value: string;
    /**
     * 
     * @type {ScreenVariantGroupReference}
     * @memberof ScreenVariant
     */
    group: ScreenVariantGroupReference;
}


