/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformScreenNoteStatusEnumToJSON = function (value: ScreenNoteStatusEnum): any {
    return value;
}

export const transformJSONToScreenNoteStatusEnum = function (value: any): ScreenNoteStatusEnum {
    return value;
}

/**
 * Status of the note
 * @export
 * @enum {string}
 */
export enum ScreenNoteStatusEnum {
    OPEN = 'open',
    RESOLVED = 'resolved'
}


