/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformScreenNotePositionToJSON = function (value: ScreenNotePosition): any {
    return {
        x: value.x,
        y: value.y,
        x_start: value.xStart,
        y_start: value.yStart
    }
}

export const transformJSONToScreenNotePosition = function (value: any): ScreenNotePosition {
    return {
        x: value.x,
        y: value.y,
        xStart: value.x_start,
        yStart: value.y_start
    }
}

/**
 * Position of the note with respect to top left corner. Values are normalized in [0, 1]
 * @export
 * @interface ScreenNotePosition
 */
export interface ScreenNotePosition {
    /**
     * The X-coordinate of the note\'s position. For area notes, this represents the X-coordinate of the end point.
     * @type {number}
     * @memberof ScreenNotePosition
     */
    x: number;
    /**
     * The Y-coordinate of the note\'s position. For area notes, this represents the Y-coordinate of the end point.
     * @type {number}
     * @memberof ScreenNotePosition
     */
    y: number;
    /**
     * The X-coordinate of the start point for area notes. Ignored for point notes.
     * @type {number}
     * @memberof ScreenNotePosition
     */
    xStart?: number;
    /**
     * The Y-coordinate of the start point for area notes. Ignored for point notes.
     * @type {number}
     * @memberof ScreenNotePosition
     */
    yStart?: number;
}


