/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformSpacingTokenColorToJSON = function (value: SpacingTokenColor): any {
    return {
        r: value.r,
        g: value.g,
        b: value.b,
        a: value.a
    }
}

export const transformJSONToSpacingTokenColor = function (value: any): SpacingTokenColor {
    return {
        r: value.r,
        g: value.g,
        b: value.b,
        a: value.a
    }
}

/**
 * 
 * @export
 * @interface SpacingTokenColor
 */
export interface SpacingTokenColor {
    /**
     * red component of the color
     * @type {number}
     * @memberof SpacingTokenColor
     */
    r: number;
    /**
     * green component of the color
     * @type {number}
     * @memberof SpacingTokenColor
     */
    g: number;
    /**
     * blue component of the color
     * @type {number}
     * @memberof SpacingTokenColor
     */
    b: number;
    /**
     * alpha component of the color
     * @type {number}
     * @memberof SpacingTokenColor
     */
    a: number;
}


