/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectTextStyleCreatedEventResource,
    transformProjectTextStyleCreatedEventResourceToJSON,
    transformJSONToProjectTextStyleCreatedEventResource
} from './project-text-style-created-event-resource';
import {
    StyleguideTextStyleEventContext,
    transformStyleguideTextStyleEventContextToJSON,
    transformJSONToStyleguideTextStyleEventContext
} from './styleguide-text-style-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformStyleguideTextStyleUpdatedEventToJSON = function (value: StyleguideTextStyleUpdatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectTextStyleCreatedEventResourceToJSON(value.resource),
        context: transformStyleguideTextStyleEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToStyleguideTextStyleUpdatedEvent = function (value: any): StyleguideTextStyleUpdatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectTextStyleCreatedEventResource(value.resource),
        context: transformJSONToStyleguideTextStyleEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface StyleguideTextStyleUpdatedEvent
 */
export interface StyleguideTextStyleUpdatedEvent {
    /**
     * 
     * @type {string}
     * @memberof StyleguideTextStyleUpdatedEvent
     */
    event: 'styleguide.text_style';
    /**
     * 
     * @type {string}
     * @memberof StyleguideTextStyleUpdatedEvent
     */
    action: 'updated';
    /**
     * 
     * @type {number}
     * @memberof StyleguideTextStyleUpdatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectTextStyleCreatedEventResource}
     * @memberof StyleguideTextStyleUpdatedEvent
     */
    resource: ProjectTextStyleCreatedEventResource;
    /**
     * 
     * @type {StyleguideTextStyleEventContext}
     * @memberof StyleguideTextStyleUpdatedEvent
     */
    context: StyleguideTextStyleEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof StyleguideTextStyleUpdatedEvent
     */
    actor: WebhookEventActor;
}


