/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectTextStyleDeletedEventResource,
    transformProjectTextStyleDeletedEventResourceToJSON,
    transformJSONToProjectTextStyleDeletedEventResource
} from './project-text-style-deleted-event-resource';
import {
    StyleguideTextStyleEventContext,
    transformStyleguideTextStyleEventContextToJSON,
    transformJSONToStyleguideTextStyleEventContext
} from './styleguide-text-style-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformStyleguideTextStyleDeletedEventToJSON = function (value: StyleguideTextStyleDeletedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectTextStyleDeletedEventResourceToJSON(value.resource),
        context: transformStyleguideTextStyleEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToStyleguideTextStyleDeletedEvent = function (value: any): StyleguideTextStyleDeletedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectTextStyleDeletedEventResource(value.resource),
        context: transformJSONToStyleguideTextStyleEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface StyleguideTextStyleDeletedEvent
 */
export interface StyleguideTextStyleDeletedEvent {
    /**
     * 
     * @type {string}
     * @memberof StyleguideTextStyleDeletedEvent
     */
    event: 'styleguide.text_style';
    /**
     * 
     * @type {string}
     * @memberof StyleguideTextStyleDeletedEvent
     */
    action: 'deleted';
    /**
     * 
     * @type {number}
     * @memberof StyleguideTextStyleDeletedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectTextStyleDeletedEventResource}
     * @memberof StyleguideTextStyleDeletedEvent
     */
    resource: ProjectTextStyleDeletedEventResource;
    /**
     * 
     * @type {StyleguideTextStyleEventContext}
     * @memberof StyleguideTextStyleDeletedEvent
     */
    context: StyleguideTextStyleEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof StyleguideTextStyleDeletedEvent
     */
    actor: WebhookEventActor;
}


