/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Styleguide,
    transformStyleguideToJSON,
    transformJSONToStyleguide
} from './styleguide';


export const transformStyleguideTextStyleEventContextToJSON = function (value: StyleguideTextStyleEventContext): any {
    return {
        styleguide: transformStyleguideToJSON(value.styleguide)
    }
}

export const transformJSONToStyleguideTextStyleEventContext = function (value: any): StyleguideTextStyleEventContext {
    return {
        styleguide: transformJSONToStyleguide(value.styleguide)
    }
}

/**
 * 
 * @export
 * @interface StyleguideTextStyleEventContext
 */
export interface StyleguideTextStyleEventContext {
    /**
     * 
     * @type {Styleguide}
     * @memberof StyleguideTextStyleEventContext
     */
    styleguide: Styleguide;
}


