/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectColorCreatedEventResource,
    transformProjectColorCreatedEventResourceToJSON,
    transformJSONToProjectColorCreatedEventResource
} from './project-color-created-event-resource';
import {
    StyleguideColorEventContext,
    transformStyleguideColorEventContextToJSON,
    transformJSONToStyleguideColorEventContext
} from './styleguide-color-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformStyleguideColorUpdatedEventToJSON = function (value: StyleguideColorUpdatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectColorCreatedEventResourceToJSON(value.resource),
        context: transformStyleguideColorEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToStyleguideColorUpdatedEvent = function (value: any): StyleguideColorUpdatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectColorCreatedEventResource(value.resource),
        context: transformJSONToStyleguideColorEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface StyleguideColorUpdatedEvent
 */
export interface StyleguideColorUpdatedEvent {
    /**
     * 
     * @type {string}
     * @memberof StyleguideColorUpdatedEvent
     */
    event: 'styleguide.color';
    /**
     * 
     * @type {string}
     * @memberof StyleguideColorUpdatedEvent
     */
    action: 'updated';
    /**
     * 
     * @type {number}
     * @memberof StyleguideColorUpdatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectColorCreatedEventResource}
     * @memberof StyleguideColorUpdatedEvent
     */
    resource: ProjectColorCreatedEventResource;
    /**
     * 
     * @type {StyleguideColorEventContext}
     * @memberof StyleguideColorUpdatedEvent
     */
    context: StyleguideColorEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof StyleguideColorUpdatedEvent
     */
    actor: WebhookEventActor;
}


