/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    User,
    transformUserToJSON,
    transformJSONToUser
} from './user';


export const transformStyleguideMemberToJSON = function (value: StyleguideMember): any {
    return {
        user: transformUserToJSON(value.user),
        role: value.role
    }
}

export const transformJSONToStyleguideMember = function (value: any): StyleguideMember {
    return {
        user: transformJSONToUser(value.user),
        role: value.role
    }
}

/**
 * 
 * @export
 * @interface StyleguideMember
 */
export interface StyleguideMember {
    /**
     * 
     * @type {User}
     * @memberof StyleguideMember
     */
    user: User;
    /**
     * The role of the user in the styleguide
     * @type {string}
     * @memberof StyleguideMember
     */
    role: 'owner' | 'admin' | 'user' | 'editor' | 'member' | 'alien';
}


