/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformStyleguideUpdateBodyToJSON = function (value: StyleguideUpdateBody): any {
    return {
        name: value.name,
        description: value.description
    }
}

export const transformJSONToStyleguideUpdateBody = function (value: any): StyleguideUpdateBody {
    return {
        name: value.name,
        description: value.description
    }
}

/**
 * 
 * @export
 * @interface StyleguideUpdateBody
 */
export interface StyleguideUpdateBody {
    /**
     * New name for the styleguide
     * @type {string}
     * @memberof StyleguideUpdateBody
     */
    name?: string;
    /**
     * New description for the styleguide
     * @type {string}
     * @memberof StyleguideUpdateBody
     */
    description?: string;
}


