/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ProjectComponentCreatedEventResource,
    transformProjectComponentCreatedEventResourceToJSON,
    transformJSONToProjectComponentCreatedEventResource
} from './project-component-created-event-resource';
import {
    StyleguideComponentEventContext,
    transformStyleguideComponentEventContextToJSON,
    transformJSONToStyleguideComponentEventContext
} from './styleguide-component-event-context';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformStyleguideComponentCreatedEventToJSON = function (value: StyleguideComponentCreatedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformProjectComponentCreatedEventResourceToJSON(value.resource),
        context: transformStyleguideComponentEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToStyleguideComponentCreatedEvent = function (value: any): StyleguideComponentCreatedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToProjectComponentCreatedEventResource(value.resource),
        context: transformJSONToStyleguideComponentEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface StyleguideComponentCreatedEvent
 */
export interface StyleguideComponentCreatedEvent {
    /**
     * 
     * @type {string}
     * @memberof StyleguideComponentCreatedEvent
     */
    event: 'styleguide.component';
    /**
     * 
     * @type {string}
     * @memberof StyleguideComponentCreatedEvent
     */
    action: 'created';
    /**
     * 
     * @type {number}
     * @memberof StyleguideComponentCreatedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {ProjectComponentCreatedEventResource}
     * @memberof StyleguideComponentCreatedEvent
     */
    resource: ProjectComponentCreatedEventResource;
    /**
     * 
     * @type {StyleguideComponentEventContext}
     * @memberof StyleguideComponentCreatedEvent
     */
    context: StyleguideComponentEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof StyleguideComponentCreatedEvent
     */
    actor: WebhookEventActor;
}


