/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    StyleguideMemberEventContext,
    transformStyleguideMemberEventContextToJSON,
    transformJSONToStyleguideMemberEventContext
} from './styleguide-member-event-context';
import {
    StyleguideMemberInvitedEventResource,
    transformStyleguideMemberInvitedEventResourceToJSON,
    transformJSONToStyleguideMemberInvitedEventResource
} from './styleguide-member-invited-event-resource';
import {
    WebhookEventActor,
    transformWebhookEventActorToJSON,
    transformJSONToWebhookEventActor
} from './webhook-event-actor';


export const transformStyleguideMemberInvitedEventToJSON = function (value: StyleguideMemberInvitedEvent): any {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformStyleguideMemberInvitedEventResourceToJSON(value.resource),
        context: transformStyleguideMemberEventContextToJSON(value.context),
        actor: transformWebhookEventActorToJSON(value.actor)
    }
}

export const transformJSONToStyleguideMemberInvitedEvent = function (value: any): StyleguideMemberInvitedEvent {
    return {
        event: value.event,
        action: value.action,
        timestamp: value.timestamp,
        resource: transformJSONToStyleguideMemberInvitedEventResource(value.resource),
        context: transformJSONToStyleguideMemberEventContext(value.context),
        actor: transformJSONToWebhookEventActor(value.actor)
    }
}

/**
 * 
 * @export
 * @interface StyleguideMemberInvitedEvent
 */
export interface StyleguideMemberInvitedEvent {
    /**
     * 
     * @type {string}
     * @memberof StyleguideMemberInvitedEvent
     */
    event: 'styleguide.member';
    /**
     * 
     * @type {string}
     * @memberof StyleguideMemberInvitedEvent
     */
    action: 'invited';
    /**
     * 
     * @type {number}
     * @memberof StyleguideMemberInvitedEvent
     */
    timestamp: number;
    /**
     * 
     * @type {StyleguideMemberInvitedEventResource}
     * @memberof StyleguideMemberInvitedEvent
     */
    resource: StyleguideMemberInvitedEventResource;
    /**
     * 
     * @type {StyleguideMemberEventContext}
     * @memberof StyleguideMemberInvitedEvent
     */
    context: StyleguideMemberEventContext;
    /**
     * 
     * @type {WebhookEventActor}
     * @memberof StyleguideMemberInvitedEvent
     */
    actor: WebhookEventActor;
}


