/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Styleguide,
    transformStyleguideToJSON,
    transformJSONToStyleguide
} from './styleguide';


export const transformStyleguideSpacingTokenEventContextToJSON = function (value: StyleguideSpacingTokenEventContext): any {
    return {
        styleguide: transformStyleguideToJSON(value.styleguide)
    }
}

export const transformJSONToStyleguideSpacingTokenEventContext = function (value: any): StyleguideSpacingTokenEventContext {
    return {
        styleguide: transformJSONToStyleguide(value.styleguide)
    }
}

/**
 * 
 * @export
 * @interface StyleguideSpacingTokenEventContext
 */
export interface StyleguideSpacingTokenEventContext {
    /**
     * 
     * @type {Styleguide}
     * @memberof StyleguideSpacingTokenEventContext
     */
    styleguide: Styleguide;
}


