/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformTokenCreateRefreshTokenBodyToJSON = function (value: TokenCreateRefreshTokenBody): any {
    return {
        grant_type: value.grantType,
        refresh_token: value.refreshToken,
        client_id: value.clientId,
        client_secret: value.clientSecret,
        code_verifier: value.codeVerifier
    }
}

export const transformJSONToTokenCreateRefreshTokenBody = function (value: any): TokenCreateRefreshTokenBody {
    return {
        grantType: value.grant_type,
        refreshToken: value.refresh_token,
        clientId: value.client_id,
        clientSecret: value.client_secret,
        codeVerifier: value.code_verifier
    }
}

/**
 * 
 * @export
 * @interface TokenCreateRefreshTokenBody
 */
export interface TokenCreateRefreshTokenBody {
    /**
     * 
     * @type {string}
     * @memberof TokenCreateRefreshTokenBody
     */
    grantType: 'refresh_token';
    /**
     * Applies when `grant_type` is `refresh_token`. The `refresh_token` you obtained while generating the access token in the first place
     * @type {string}
     * @memberof TokenCreateRefreshTokenBody
     */
    refreshToken: string;
    /**
     * The `client_id` of your Zeplin app
     * @type {string}
     * @memberof TokenCreateRefreshTokenBody
     */
    clientId: string;
    /**
     * The `client_secret` of your Zeplin app  **Note**: `client_secret` is required for `code` values obtained without using a PKCE `code_challenge` value.  **Warning**: `client_secret` property should only be used in a server-side application.  If your Zeplin app is a public client, you should use PKCE authorization flow. 
     * @type {string}
     * @memberof TokenCreateRefreshTokenBody
     */
    clientSecret?: string;
    /**
     * A cryptographically random string that is used to correlate the authorization request to the token request
     * @type {string}
     * @memberof TokenCreateRefreshTokenBody
     */
    codeVerifier?: string;
}


