/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformTokenResponseToJSON = function (value: TokenResponse): any {
    return {
        access_token: value.accessToken,
        expires_in: value.expiresIn,
        refresh_token: value.refreshToken,
        refresh_expires_in: value.refreshExpiresIn,
        token_type: value.tokenType
    }
}

export const transformJSONToTokenResponse = function (value: any): TokenResponse {
    return {
        accessToken: value.access_token,
        expiresIn: value.expires_in,
        refreshToken: value.refresh_token,
        refreshExpiresIn: value.refresh_expires_in,
        tokenType: value.token_type
    }
}

/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * Access token that allows you to make requests to the API on behalf of a user
     * @type {string}
     * @memberof TokenResponse
     */
    accessToken: string;
    /**
     * Access token\'s lifetime in seconds
     * @type {number}
     * @memberof TokenResponse
     */
    expiresIn: number;
    /**
     * Refresh token that allows you to obtain access tokens
     * @type {string}
     * @memberof TokenResponse
     */
    refreshToken: string;
    /**
     * Refresh token\'s lifetime in seconds
     * @type {number}
     * @memberof TokenResponse
     */
    refreshExpiresIn: number;
    /**
     * Type of the token returned
     * @type {string}
     * @memberof TokenResponse
     */
    tokenType: string;
}


