/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    UserWebhookEventEnum,
    transformUserWebhookEventEnumToJSON,
    transformJSONToUserWebhookEventEnum
} from './user-webhook-event-enum';
import {
    WebhookStatusEnum,
    transformWebhookStatusEnumToJSON,
    transformJSONToWebhookStatusEnum
} from './webhook-status-enum';


export const transformUserWebhookUpdateBodyToJSON = function (value: UserWebhookUpdateBody): any {
    return {
        url: value.url,
        name: value.name,
        secret: value.secret,
        status: value.status && transformWebhookStatusEnumToJSON(value.status),
        project_ids: value.projectIds && [...value.projectIds],
        styleguide_ids: value.styleguideIds && [...value.styleguideIds],
        events: value.events && [...value.events].map(transformUserWebhookEventEnumToJSON)
    }
}

export const transformJSONToUserWebhookUpdateBody = function (value: any): UserWebhookUpdateBody {
    return {
        url: value.url,
        name: value.name,
        secret: value.secret,
        status: value.status && transformJSONToWebhookStatusEnum(value.status),
        projectIds: value.project_ids && new Set(value.project_ids),
        styleguideIds: value.styleguide_ids && new Set(value.styleguide_ids),
        events: value.events && new Set(value.events.map(transformJSONToUserWebhookEventEnum))
    }
}

/**
 * 
 * @export
 * @interface UserWebhookUpdateBody
 */
export interface UserWebhookUpdateBody {
    /**
     * The URL of the webhook
     * @type {string}
     * @memberof UserWebhookUpdateBody
     */
    url?: string;
    /**
     * The name of the webhook
     * @type {string}
     * @memberof UserWebhookUpdateBody
     */
    name?: string;
    /**
     * The secret to be used to generate signatures for webhook requests
     * @type {string}
     * @memberof UserWebhookUpdateBody
     */
    secret?: string;
    /**
     * 
     * @type {WebhookStatusEnum}
     * @memberof UserWebhookUpdateBody
     */
    status?: WebhookStatusEnum;
    /**
     * The project ids of the webhook
     * @type {Set<string>}
     * @memberof UserWebhookUpdateBody
     */
    projectIds?: Set<string>;
    /**
     * The styleguide ids of the webhook
     * @type {Set<string>}
     * @memberof UserWebhookUpdateBody
     */
    styleguideIds?: Set<string>;
    /**
     * The events of the webhook
     * @type {Set<UserWebhookEventEnum>}
     * @memberof UserWebhookUpdateBody
     */
    events?: Set<UserWebhookEventEnum>;
}


