/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    UserWebhookEventEnum,
    transformUserWebhookEventEnumToJSON,
    transformJSONToUserWebhookEventEnum
} from './user-webhook-event-enum';
import {
    WebhookStatusEnum,
    transformWebhookStatusEnumToJSON,
    transformJSONToWebhookStatusEnum
} from './webhook-status-enum';


export const transformUserWebhookCreateBodyToJSON = function (value: UserWebhookCreateBody): any {
    return {
        url: value.url,
        name: value.name,
        secret: value.secret,
        status: value.status && transformWebhookStatusEnumToJSON(value.status),
        project_ids: [...value.projectIds],
        styleguide_ids: [...value.styleguideIds],
        events: [...value.events].map(transformUserWebhookEventEnumToJSON)
    }
}

export const transformJSONToUserWebhookCreateBody = function (value: any): UserWebhookCreateBody {
    return {
        url: value.url,
        name: value.name,
        secret: value.secret,
        status: value.status && transformJSONToWebhookStatusEnum(value.status),
        projectIds: new Set(value.project_ids),
        styleguideIds: new Set(value.styleguide_ids),
        events: new Set(value.events.map(transformJSONToUserWebhookEventEnum))
    }
}

/**
 * 
 * @export
 * @interface UserWebhookCreateBody
 */
export interface UserWebhookCreateBody {
    /**
     * The URL of the webhook
     * @type {string}
     * @memberof UserWebhookCreateBody
     */
    url: string;
    /**
     * The name of the webhook
     * @type {string}
     * @memberof UserWebhookCreateBody
     */
    name?: string;
    /**
     * The secret to be used to generate signatures for webhook requests
     * @type {string}
     * @memberof UserWebhookCreateBody
     */
    secret: string;
    /**
     * 
     * @type {WebhookStatusEnum}
     * @memberof UserWebhookCreateBody
     */
    status?: WebhookStatusEnum;
    /**
     * The project ids of the webhook
     * @type {Set<string>}
     * @memberof UserWebhookCreateBody
     */
    projectIds: Set<string>;
    /**
     * The styleguide ids of the webhook
     * @type {Set<string>}
     * @memberof UserWebhookCreateBody
     */
    styleguideIds: Set<string>;
    /**
     * The events of the webhook
     * @type {Set<UserWebhookEventEnum>}
     * @memberof UserWebhookCreateBody
     */
    events: Set<UserWebhookEventEnum>;
}


