/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformUserWebhookEventEnumToJSON = function (value: UserWebhookEventEnum): any {
    return value;
}

export const transformJSONToUserWebhookEventEnum = function (value: any): UserWebhookEventEnum {
    return value;
}

/**
 * 
 * @export
 * @enum {string}
 */
export enum UserWebhookEventEnum {
    STAR = '*',
    PROJECT = 'project.*',
    PROJECT_COLOR = 'project.color',
    PROJECT_COMPONENT = 'project.component',
    PROJECT_MEMBER = 'project.member',
    PROJECT_NOTE = 'project.note',
    PROJECT_NOTE_COMMENT = 'project.note.comment',
    PROJECT_NOTE_COMMENT_REACTION = 'project.note.comment.reaction',
    PROJECT_SCREEN = 'project.screen',
    PROJECT_SCREEN_VERSION = 'project.screen.version',
    PROJECT_SPACING_TOKEN = 'project.spacing_token',
    PROJECT_TEXT_STYLE = 'project.text_style',
    STYLEGUIDE = 'styleguide.*',
    STYLEGUIDE_COLOR = 'styleguide.color',
    STYLEGUIDE_COMPONENT = 'styleguide.component',
    STYLEGUIDE_MEMBER = 'styleguide.member',
    STYLEGUIDE_SPACING_TOKEN = 'styleguide.spacing_token',
    STYLEGUIDE_TEXT_STYLE = 'styleguide.text_style',
    WORKSPACE = 'workspace.*',
    WORKSPACE_NOTIFICATION = 'workspace.notification',
    WORKSPACE_PROJECT = 'workspace.project',
    WORKSPACE_STYLEGUIDE = 'workspace.styleguide'
}


