/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformVariableInfoToJSON = function (value: VariableInfo): any {
    return {
        source_id: value.sourceId,
        collection_source_id: value.collectionSourceId
    }
}

export const transformJSONToVariableInfo = function (value: any): VariableInfo {
    return {
        sourceId: value.source_id,
        collectionSourceId: value.collection_source_id
    }
}

/**
 * 
 * @export
 * @interface VariableInfo
 */
export interface VariableInfo {
    /**
     * The source id of the variable
     * @type {string}
     * @memberof VariableInfo
     */
    sourceId: string;
    /**
     * The source id of the collection that the variable belongs to
     * @type {string}
     * @memberof VariableInfo
     */
    collectionSourceId: string;
}


