/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    ResourceSource,
    transformResourceSourceToJSON,
    transformJSONToResourceSource
} from './resource-source';
import {
    VariableGroup,
    transformVariableGroupToJSON,
    transformJSONToVariableGroup
} from './variable-group';
import {
    VariableMode,
    transformVariableModeToJSON,
    transformJSONToVariableMode
} from './variable-mode';


export const transformVariableCollectionToJSON = function (value: VariableCollection): any {
    return {
        id: value.id,
        created: value.created,
        name: value.name,
        description: value.description,
        modes: value.modes.map(transformVariableModeToJSON),
        groups: value.groups.map(transformVariableGroupToJSON),
        source_id: value.sourceId,
        source: value.source && transformResourceSourceToJSON(value.source)
    }
}

export const transformJSONToVariableCollection = function (value: any): VariableCollection {
    return {
        id: value.id,
        created: value.created,
        name: value.name,
        description: value.description,
        modes: value.modes.map(transformJSONToVariableMode),
        groups: value.groups.map(transformJSONToVariableGroup),
        sourceId: value.source_id,
        source: value.source && transformJSONToResourceSource(value.source)
    }
}

/**
 * 
 * @export
 * @interface VariableCollection
 */
export interface VariableCollection {
    /**
     * The unique id of the variable collection
     * @type {string}
     * @memberof VariableCollection
     */
    id: string;
    /**
     * The unix timestamp when the variable collection was created
     * @type {number}
     * @memberof VariableCollection
     */
    created: number;
    /**
     * The name of the variable collection
     * @type {string}
     * @memberof VariableCollection
     */
    name: string;
    /**
     * The description of the variable collection
     * @type {string}
     * @memberof VariableCollection
     */
    description?: string;
    /**
     * 
     * @type {Array<VariableMode>}
     * @memberof VariableCollection
     */
    modes: Array<VariableMode>;
    /**
     * 
     * @type {Array<VariableGroup>}
     * @memberof VariableCollection
     */
    groups: Array<VariableGroup>;
    /**
     * Variable collection\'s identifier in the design tool
     * @type {string}
     * @memberof VariableCollection
     */
    sourceId: string;
    /**
     * 
     * @type {ResourceSource}
     * @memberof VariableCollection
     */
    source?: ResourceSource;
}


