/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformVariableValueTypeEnumToJSON = function (value: VariableValueTypeEnum): any {
    return value;
}

export const transformJSONToVariableValueTypeEnum = function (value: any): VariableValueTypeEnum {
    return value;
}

/**
 * Variable value types
 * @export
 * @enum {string}
 */
export enum VariableValueTypeEnum {
    COLOR = 'color'
}


