/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformVersionCommitColorToJSON = function (value: VersionCommitColor): any {
    return {
        r: value.r,
        g: value.g,
        b: value.b,
        a: value.a
    }
}

export const transformJSONToVersionCommitColor = function (value: any): VersionCommitColor {
    return {
        r: value.r,
        g: value.g,
        b: value.b,
        a: value.a
    }
}

/**
 * 
 * @export
 * @interface VersionCommitColor
 */
export interface VersionCommitColor {
    /**
     * red component of the color
     * @type {number}
     * @memberof VersionCommitColor
     */
    r: number;
    /**
     * green component of the color
     * @type {number}
     * @memberof VersionCommitColor
     */
    g: number;
    /**
     * blue component of the color
     * @type {number}
     * @memberof VersionCommitColor
     */
    b: number;
    /**
     * alpha component of the color
     * @type {number}
     * @memberof VersionCommitColor
     */
    a: number;
}


