/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const transformWorkspaceProjectDeletedEventResourceToJSON = function (value: WorkspaceProjectDeletedEventResource): any {
    return {
        id: value.id,
        type: value.type
    }
}

export const transformJSONToWorkspaceProjectDeletedEventResource = function (value: any): WorkspaceProjectDeletedEventResource {
    return {
        id: value.id,
        type: value.type
    }
}

/**
 * 
 * @export
 * @interface WorkspaceProjectDeletedEventResource
 */
export interface WorkspaceProjectDeletedEventResource {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceProjectDeletedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceProjectDeletedEventResource
     */
    type: 'Project';
}


