/* tslint:disable */
/* eslint-disable */
/**
 * Zeplin API
 * Access your resources in Zeplin
 *
 * Contact: support@zeplin.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    Styleguide,
    transformStyleguideToJSON,
    transformJSONToStyleguide
} from './styleguide';


export const transformWorkspaceStyleguideCreatedEventResourceToJSON = function (value: WorkspaceStyleguideCreatedEventResource): any {
    return {
        id: value.id,
        type: value.type,
        data: transformStyleguideToJSON(value.data)
    }
}

export const transformJSONToWorkspaceStyleguideCreatedEventResource = function (value: any): WorkspaceStyleguideCreatedEventResource {
    return {
        id: value.id,
        type: value.type,
        data: transformJSONToStyleguide(value.data)
    }
}

/**
 * 
 * @export
 * @interface WorkspaceStyleguideCreatedEventResource
 */
export interface WorkspaceStyleguideCreatedEventResource {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceStyleguideCreatedEventResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceStyleguideCreatedEventResource
     */
    type: 'Styleguide';
    /**
     * 
     * @type {Styleguide}
     * @memberof WorkspaceStyleguideCreatedEventResource
     */
    data: Styleguide;
}


